### ISSUE TITLE
Add a Checkbox to Items on the List

### ISSUE THREAD

**Issue by Cosmo304** [NinSam/To-Do-List#1]
It would be nice to add a checkbox to the side of the item so that you can check off things as you get them done. This would be nice and I think it would make you feel good about yourself if you have the satisfaction of checking off things that you finished!

**Comment by NinSam** [comment]
Thanks for the suggestion I will try to add that along with android and mac support

**Comment by Cosmo304** [comment]
Ok! Thanks!
